Task 4.6 partly done
alexb82/surf-flutter-course-balashov pull request #10
Opened 2020-12-27 13:52 UTC by alexb82

Нужна помощь
1. Не смог заставить изменить стиль неактивного таба  , от      unselectedLabelStyle: TextStyle(color: Colors.red, fontSize: 14), текст не красится. Подскажите, плз, как это правильно сделать.
2. Боттомбар пока сделал как набор одинаковых иконок, но активная поднимается выше - как заставить ее стоять вровень с остальными ?
Остальное прикладываю
![Screenshot_1609076590](https://user-images.githubusercontent.com/11836507/103172329-c0e30e00-4863-11eb-95f9-5433526c1ba0.png)
![Screenshot_1609075378](https://user-images.githubusercontent.com/11836507/103172332-c8a2b280-4863-11eb-9980-b3fff22bcadb.png)
![Screenshot_1609076731](https://user-images.githubusercontent.com/11836507/103172339-d1938400-4863-11eb-8694-bdfacba08af3.png)
![Screenshot_1609075381](https://user-images.githubusercontent.com/11836507/103172343-d6f0ce80-4863-11eb-9940-1802b9591c0f.png)

2020-12-28 07:09 UTC, alexb82 commented
На свежую голову разобрался ) Еще один коммит выкатил
![Screenshot_1609139243](https://user-images.githubusercontent.com/11836507/103196180-bd4b9780-48f4-11eb-8e41-0378ea1b9028.png)

2020-12-28 08:49 UTC, artem-zaitsev requested changes
Надо поправить и разобраться с TabBar. Все должно работать с без особых проблем.

2020-12-28 08:49 UTC, artem-zaitsev commented on lib/UI/screen/sight_card.dart
> +                ImageChunkEvent loadingProgress) {
про запятые не забывайте

2020-12-28 08:49 UTC, artem-zaitsev commented on lib/UI/screen/sight_card.dart
> +  final String cardtype;
Лушче сделать enum

2020-12-28 08:49 UTC, artem-zaitsev commented on lib/UI/screen/visiting_screen.dart
> +    return (Text(
1. что-то пошло не так с форматированием
2. Зачем оборачивать в ()?

2020-12-28 08:49 UTC, artem-zaitsev commented on lib/UI/screen/visiting_screen.dart
> +class NotColoredText extends StatelessWidget {
где документация/описание?

2020-12-28 08:49 UTC, artem-zaitsev commented on lib/common/bottomnavbar.dart
> +    return BottomNavigationBar(
Приедется сделать кастомный боттом бар. Просто кнопки в ряд.

2020-12-28 08:49 UTC, artem-zaitsev commented on lib/UI/screen/visiting_screen.dart
> +            child: TabBar(
1. Поставьте еще и labelColor. Вероятнее всего, отдельно не сработают.
2. Для более оперативного ответа - в чат.

2020-12-28 15:28 UTC, alexb82 commented
Переделал на кастомный боттомбар и устранил замечания
![Screenshot_1609169028](https://user-images.githubusercontent.com/11836507/103225199-7da79e80-493a-11eb-90de-c006b758b559.png)

2020-12-29 09:17 UTC, artem-zaitsev approved these changes
Небольшие комменты перед слиянием сиправьте

2020-12-29 09:17 UTC, artem-zaitsev commented on lib/UI/screen/sight_card.dart
> +enum Cardtype {
Для классов PascalCase

2020-12-29 09:17 UTC, artem-zaitsev commented on lib/UI/screen/sight_card.dart
> +  final cardtype;
cardType

2020-12-29 09:17 UTC, artem-zaitsev commented on lib/UI/screen/sight_card.dart
> +    if (cardtype == Cardtype.basic) return SizedBox.shrink();
switch ... case здесь куда удобнее

2020-12-29 09:17 UTC, artem-zaitsev commented on lib/UI/screen/sight_card.dart
> +    if (cardtype == Cardtype.basic) return _buildAddToFavIcon(context);
switch case

2020-12-29 09:17 UTC, artem-zaitsev commented on lib/common/bottomnavbar.dart
> +              InkWell(
на будущее: можно передавать список кнопок на вход. А здесь иметь только размещение. Но пока ок

2020-12-29 16:22 UTC, merged